### ISSUE TITLE
Integrate with Code Quality Services

### ISSUE THREAD

**Issue by filfreire** [petiaccja/Inline-Engine#23]
I suggest after handling #21 and #22 and afterward:

Try to integrate with a few Code Quality free services:
- https://codecov.io
- https://www.codacy.com
- https://codebeat.co

That way you'll have an overall perspective (though not a complete one) of the codebase health/quality status at all times.

Also, add the badges of those services to the README. It always adds to the credibility of the project.

/cc @petiaccja @Yours3lf @hsdxpro

**Comment by petiaccja** [comment]
Hi,
First of all, I would to thank you for your suggestions.
I have to admit that I'm a little skeptical with these tools and methodologies. I can understand they work well for simpler languages and (complex) programs with different requirements, but I can't seem to see a way to get them together with a C++ game engine.
For the code coverage, tools are not able give meaningful results for template code, which is heavily used in the engine. The problem is that uncompiled template code will never show up among debug symbols, resulting in 100% coverage. Additionally, coverage tools can't know if the template has been instantiated with "enough" different arguments.
Another blow for code coverage is that it mostly goes well with unit tests, which, well, we don't quite have. While the utilities (BaseLibrary) can (and should) be unit tested, other parts of the engine are a tougher job. The key to unit testing is dependency injection and decoupling, which the engine indeed tries to follow. An overwhelming part of the code uses concrete classes for injection, because there is no need for interfaces. Forcing all these to be interfaces would highly bloat the code and encourage heap allocation at many places, where it's not justified. This would make code less readable and slower.
As a rough estimate, these transforms would increase code size by at least 50%. I don't think it's justified when the integration test catches major bugs, and the subtle bugs would slip through unit tests too. This being said, the integration test could be automatized, and code coverage taken from that.
I decided to give Codacy a shot. It reports near perfect scores (90%+), and only 4 critical bugs in the code. A while ago, I also ran CppDepend on the codebase, which reported much worse scores. While these tools give rise to some concerns, they don't quite seem to understand the code (Codacy being too accepting, CppDepend complaining too much). I will leave Codacy enabled.
Do you have any suggestions as to where one can read more about these practices, preferably real-world case studies?
Cheers, Péter

**Comment by filfreire** [comment]
Hi @petiaccja forgot to reply back to you in this issue.

Here's some recent reading I recommend:
- https://cacm.acm.org/blogs/blog-cacm/229942-blame-free-quality-control/fulltext
- https://www.yegor256.com/2018/03/06/speed-vs-quality.html
- and the book [Code Ahead](https://www.amazon.com/dp/1982063742)

Also another suggestion - since you're using codacy, add it's badge to the project's README:
<img width="1284" alt="badge" src="https://user-images.githubusercontent.com/11976836/50540977-7ce99f80-0b9c-11e9-8476-d972436f68d9.png">


Take care 👍

**Comment by petiaccja** [comment]
Hi @filfreire, 
Interesting reads, thanks for your help!
