### ISSUE TITLE
About the invitation email...

### ISSUE THREAD

**Issue by zlixine** [petiaccja/Inline-Engine#30]
Today I got an email from highskilledprogrammer@gmail.com, asking me to join developing this engine, I am curious about the engine roadmap and structures , afaik it seems like you are targeting dx11 capable gpus? (with tessellation) which immediately breaks compatibility on mobile devices and macos is that right? If not I am sad to tell you I can't join because "indie & beginner not AAA titles" mobile gaming is way bigger than pc or even console and the revenue is much larger especially to startup promising engines like this.

Also why did you select me? Or did you just send an email to many other by bot?

**Comment by zlixine** [comment]
Also DX12 usage is limited to win 10 only and using too many templates which cause code bloat and unwanted behaviours and heap allocated objects and interfaces aren't cheap and excessive use of them cause lag and slows the game and the architecture isn't pretty at all.

**Comment by hsdxpro** [comment]
Hi, we are targeting DirectX12 & Vulkan -> Pc (Windows, Linux, Mac), Console, really high end mobile devices maybe. Tesselation is available on mobile devices since OpenGL ES 3.1 also from Metal 1.0 or 1.2 there is tesselation. We are not only targeting gaming, but other fields in filming and any interactive entertainment, like Unity and UE4 do.

I searched for "Game Engine" via github page, and from day to day I'm searching for good candidates.

**Comment by hsdxpro** [comment]
I think our Graph based pipeline is pretty and well designed, we used templates where feasible, leaving no runtime cost behind. heap allocated objects aren't cheap? What if we overload the new keyword? interfaces aren't cheap? It's cheap compared to the calculations done in one frame, and there are other patterns which we can use instead of interface, but trust my this will be not a bottleneck...

**Comment by hsdxpro** [comment]
Contact me at hsdxpro@gmail.com if you are interested.

**Comment by zlixine** [comment]
You are limiting your user database already? This is a promising small game engine with focus to finish it and get audience, targeting high end devices isn't beneficial for you, and you should consider getting more catchy unique name searching inline on google have many results...

**Comment by hsdxpro** [comment]
Targeting non high end devices is boring. Our name isn't catchy but our fate isn't defined by our name.

**Comment by zlixine** [comment]
Boring? Unity "the most famous" targets low end dx9 as well as high end, also the API never made a game prettier or uglier it depends on the developer himself and most of award winning games were designed for mid end devices dx10 capable, for example gta iv , v on PC is a shit due to bad port and design while cod and bf or fallout are absolute masterpieces which don't even require 8 gbs of ram, slowing down operations due to bad design require more powerful pc to run the game that's why most games have high requirements cause of their shitty developers, anything done on a high end can be done on low end but with careful and well designed engine ignoring good architecture and design require more powerful pc

**Comment by hsdxpro** [comment]
Look we target highest end, that doesn't mean the user will not be able to decrease the graphics for his mid level gaming pc. We know it's important to reach wide audience don't worry. Agree, our engine will be high performance, we have the knowledge and experience. We are just aiming for super crazy graphics in our tech demo + benchmark software which should be slow on the best computers too. Because we will use tons of well optimized shaders. Not just some of them.
